### ISSUE TITLE
Trouble with Amazon aws : SMTPAuthenticationError: (530, 'Must issue a STARTTLS command first')

### ISSUE THREAD

**Issue by sidx** [Pylons/pyramid_exclog#24]
I successfully used my aws credentials to send an email.
But when I use it in exclog to send a mail it returns an error:
SMTPAuthenticationError: (530, 'Must issue a STARTTLS command first').

This is the code-

[handler_exc_handler]
class = handlers.SMTPHandler
args = (('email-smtp.us-east-1.amazonaws.com', 587), 'no-reply@apnistreet.com',  'sidharth@apnistreet.com'], 'Apnistreet Exception', ('username','user key'))
level = ERROR
formatter = exc_formatter

Could you perhaps look into it and say whether its exclog's problem or mine?

**Comment by tseaver** [comment]
@sidx `handlers.SMTPHandler` is a Python stdlib object.  To get it to talk TLS/SSL, you need to [configure it's `secure` argument](https://docs.python.org/2/library/logging.handlers.html#smtphandler).
