### ISSUE TITLE
as_globals_list enforcing a list of strings

### ISSUE THREAD

**Issue by raverat** [Pylons/pyramid_exclog#34]
Hi,

I noticed that the function **as_globals_list** in [__init__.py](https://github.com/Pylons/pyramid_exclog/blob/master/pyramid_exclog/__init__.py#L21) file is using the **maybe_resolve** method from the _resolver_, this allows to pass a string that needs to be imported or directly a class which will be untouched.

```python
def as_globals_list(value):
    ...
    value = aslist(value)
    for dottedname in value:
        ...
        resolver.maybe_resolve(dottedname)
```

However, the method used before the for loop **aslist()** assumed that everything is a string. Could we follow the same logic that **maybe_resolve** and handle the case where the value is a class directly?

**Comment by mmerickel** [comment]
If you want to propose a change to aslist you'll need to do that in Pyramid. I think it would be an acceptable change.

I don't think it's unreasonable to avoid calling split() on values that are not strings in a similar way to how aslist_cronly avoids doing anything unless the value is actually a string.

https://github.com/Pylons/pyramid/blob/0a9d1403bd20c28ca3fb336bd65e2899de356bbb/src/pyramid/settings.py#L23-L34

**Comment by raverat** [comment]
Thanks for your reply!
